In [4]:
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score

import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import to_categorical
# load dataset
dataset = pd.read_excel("/content/balanced_cleaned_pollution_dataset.xlsx") # I used colab to save the data
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

# Feature Scaling
sc = StandardScaler()
X_scaled = sc.fit_transform(X)



# Encode string labels to integers
le = LabelEncoder()
y_encoded = le.fit_transform(y)

# One-hot encoding as the our data is multiclass target
num_classes = len(np.unique(y_encoded))
y_categorical = to_categorical(y_encoded, num_classes)



# K-Fold Cross-Validation setup
kfold = KFold(n_splits=5, shuffle=True, random_state=42) # shuffle = True mean that it choose the data randomly and k = 5 based on our data
# these data to store everything form the summary
fold_accuracies = []
fold_precisions = []
fold_recalls = []

fold_index = 1
for train_idx, val_idx in kfold.split(X_scaled, y_categorical):
    print(f"\n--- Fold {fold_index} ---")

    # Build model
    model = Sequential()
    model.add(Dense(64, activation='relu', input_shape=(X.shape[1],)))
    model.add(Dense(32, activation='relu'))
    model.add(Dense(num_classes, activation='softmax')) # as it is the last layer

    # Compile model with adam as optimizer(as suggested in the slides ) and loss function and metrics for evalution
    model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

    # Train model
    model.fit(X_scaled[train_idx], y_categorical[train_idx], epochs=10, batch_size=32, verbose=0)

    # Predict and evaluate
    y_pred = model.predict(X_scaled[val_idx])
    y_pred_classes = np.argmax(y_pred, axis=1)
    y_true_classes = np.argmax(y_categorical[val_idx], axis=1)

    # Compute confusion matrix and metrics
    cm = confusion_matrix(y_true_classes, y_pred_classes)
    accuracy = accuracy_score(y_true_classes, y_pred_classes)
    precision = precision_score(y_true_classes, y_pred_classes, average='weighted')
    recall = recall_score(y_true_classes, y_pred_classes, average='weighted')


    # Print results for current fold
    print("Confusion Matrix:")
    print(cm)
    print(f"Accuracy: {accuracy:.2f}")
    print(f"Precision: {precision:.2f}")
    print(f"Recall: {recall:.2f}")


    # Store metrics
    fold_accuracies.append(accuracy)
    fold_precisions.append(precision)
    fold_recalls.append(recall)
    # to move ito the next data
    fold_index += 1

# Final average metrics
print("\n Cross-Validation Summary ")
print(f"Average Accuracy: {np.mean(fold_accuracies):.4f}")
print(f"Average Precision: {np.mean(fold_precisions):.4f}")
print(f"Average Recall: {np.mean(fold_recalls):.4f}")



--- Fold 1 ---


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
Confusion Matrix:
[[334   0   0   0]
 [  0 180   0  30]
 [  4   0 202  10]
 [  0  15   9 164]]
Accuracy: 0.93
Precision: 0.93
Recall: 0.93

--- Fold 2 ---


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
Confusion Matrix:
[[336   0   0   0]
 [  0 141   0  25]
 [  0   0 239  12]
 [  0  21  10 164]]
Accuracy: 0.93
Precision: 0.93
Recall: 0.93

--- Fold 3 ---


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
Confusion Matrix:
[[309   0   0   0]
 [  0 176   0  17]
 [  7   0 240  10]
 [  0  37  12 140]]
Accuracy: 0.91
Precision: 0.91
Recall: 0.91

--- Fold 4 ---


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
Confusion Matrix:
[[345   0   0   0]
 [  0 163   0  24]
 [  0   0 219   9]
 [  0  27  12 149]]
Accuracy: 0.92
Precision: 0.92
Recall: 0.92

--- Fold 5 ---


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
Confusion Matrix:
[[334   0   1   0]
 [  0 178   0  14]
 [  2   0 223   8]
 [  0  38  14 136]]
Accuracy: 0.92
Precision: 0.92
Recall: 0.92

 Cross-Validation Summary 
Average Accuracy: 0.9224
Average Precision: 0.9228
Average Recall: 0.9224
